name = "playground"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
routes = [
	{ pattern = "takumaaa.dev", custom_domain = true }
]

[site]
bucket = ".output/public"
