name: Cloudflare

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: bun i

      - name: Run Tests
        run: bun run test

      - name: Build
        run: bun run build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
