name: Cloudflare

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          version: 1.0.1

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: bun i

      - name: Build
        run: bun run build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
